name: common_utils_services
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  flutter_tts: ^4.2.3
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.0
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  retrofit: ^4.0.3
  dio: ^5.4.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  freezed: ^2.4.6
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
